#!/usr/bin/env python3
"""Retrieve relevant private corpus notes without publishing the corpus.

The script expects a local corpus manifest generated by `fetch_wechat_articles.py`.
It prints compact JSON with article metadata and short snippets only. Keep the
corpus directory private and outside the public repository.
"""

import argparse
import json
import math
import re
from collections import Counter
from pathlib import Path


STOPWORDS = {
    "为什么", "如何", "是不是", "什么", "一个", "我们", "你们", "他们", "自己",
    "这个", "那个", "以及", "如果", "因为", "所以", "但是", "不是", "而是",
}


def tokenize(text: str):
    words = re.findall(r"[A-Za-z0-9+#.]{2,}|[\u4e00-\u9fff]{2,}", text)
    tokens = []
    for word in words:
        if word in STOPWORDS:
            continue
        if re.fullmatch(r"[\u4e00-\u9fff]{4,}", word):
            tokens.extend(word[i : i + 2] for i in range(len(word) - 1))
            tokens.extend(word[i : i + 3] for i in range(len(word) - 2))
        else:
            tokens.append(word.lower())
    return tokens


def read_body(path: str):
    text = Path(path).read_text(encoding="utf-8", errors="ignore")
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            text = parts[2]
    text = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", text)
    text = re.sub(r"^# .*$", "", text, flags=re.M)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def paragraphs(text: str):
    return [re.sub(r"\s+", " ", p).strip() for p in re.split(r"\n\s*\n+", text) if len(p.strip()) >= 30]


def cosine(a: Counter, b: Counter):
    if not a or not b:
        return 0.0
    common = set(a) & set(b)
    numerator = sum(a[t] * b[t] for t in common)
    denom = math.sqrt(sum(v * v for v in a.values())) * math.sqrt(sum(v * v for v in b.values()))
    return numerator / denom if denom else 0.0


def best_snippets(body: str, query_tokens: set, limit: int = 2):
    scored = []
    for p in paragraphs(body):
        toks = set(tokenize(p))
        overlap = len(toks & query_tokens)
        if overlap:
            scored.append((overlap, len(p), p))
    scored.sort(key=lambda x: (-x[0], x[1]))
    return [p[:220] + ("..." if len(p) > 220 else "") for _, _, p in scored[:limit]]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True, help="Path to private corpus manifest.json")
    parser.add_argument("--query", required=True)
    parser.add_argument("--top-k", type=int, default=5)
    args = parser.parse_args()

    manifest = [x for x in json.loads(Path(args.manifest).read_text(encoding="utf-8")) if x.get("word_count", 0) > 0]
    query_tokens = tokenize(args.query)
    query_vec = Counter(query_tokens)
    results = []

    for item in manifest:
        body = read_body(item["markdown"])
        title = item.get("title", "")
        text = f"{title}\n{body}"
        vec = Counter(tokenize(text))
        score = cosine(query_vec, vec)
        if score <= 0:
            continue
        results.append({
            "score": round(score, 4),
            "title": title,
            "publish_time": item.get("publish_time"),
            "word_count": item.get("word_count"),
            "url": item.get("url"),
            "snippets": best_snippets(body, set(query_tokens)),
        })

    results.sort(key=lambda x: x["score"], reverse=True)
    print(json.dumps({
        "query": args.query,
        "top_k": args.top_k,
        "results": results[: args.top_k],
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
